### ISSUE TITLE
Warning: Unexpected input(s) 

### ISSUE THREAD

**Issue by MrGreensWorkshop** [lucasbento/auto-close-issues#13]
## Environment

ubuntu-latest of GitHub Actions

## Upgrading version

not upgrading, using v1.0.2

## Description

issue not closed and this warning appears

Warning: Unexpected input(s) 'issue-close-message', 'closed-issues-label', valid inputs are ['github-token']

## Reproducible demo

Workflow: https://github.com/MrGreensWorkshop/issue_closer_test/blob/main/.github/workflows/main.yml

issue: https://github.com/MrGreensWorkshop/issue_closer_test/issues/2

log: https://github.com/MrGreensWorkshop/issue_closer_test/actions/runs/2142509069

related with #8 ?

**Comment by karikera** [comment]
```
(node:1[5](https://github.com/karikera/test/runs/8113457210?check_suite_focus=true#step:3:6)[6](https://github.com/karikera/test/runs/8113457210?check_suite_focus=true#step:3:7)3) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: input should be a markdown string
    at mdjson (/home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:10464:10)
    at /home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:10048:39
    at Object.6[7](https://github.com/karikera/test/runs/8113457210?check_suite_focus=true#step:3:8)6 (/home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:1012[8](https://github.com/karikera/test/runs/8113457210?check_suite_focus=true#step:3:9):3)
    at __webpack_require__ (/home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:22:30)
    at startup (/home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:37:1[9](https://github.com/karikera/test/runs/8113457210?check_suite_focus=true#step:3:10))
    at /home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:43:18
    at Object.<anonymous> (/home/runner/work/_actions/lucasbento/auto-close-issues/v1.0.2/dist/index.js:46:[10](https://github.com/karikera/test/runs/8113457210?check_suite_focus=true#step:3:11))
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
```

**Comment by ergo720** [comment]
@MrGreensWorkshop Yes, those are the same warnings that were fixed in https://github.com/lucasbento/auto-close-issues/pull/4. The issue is that the author of this action has not released a new version which includes the fix, so the latest release is still affected. To solve it, you simply need to use the latest commit of this repository, instead of the latest release. This would be `lucasbento/auto-close-issues@28e2d2bff4035cd60111c3e1fa4d0145875fabd9`

**Comment by MrGreensWorkshop** [comment]
@ergo720 Thanks for the tip. Since the repo looks like unmaintained. I will close the issue.
